apiVersion: v1
kind: Service
metadata:
  name: svc-2024mt03517
spec:
  type: LoadBalancer
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
